[package]
name = "serveur"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.24"
env_logger = "0.10.0"
http-body-util = "0.1.0-rc.3"
hyper = "0.14.27"
hyper-util = "0.0.0"
json = "0.12.4"
log = "0.4.19"
reqwest = { version = "0.11.16", features = ["blocking", "json"] }
simple_http_parser = "0.3.2"
tokio = "1.29.1"
